# Generated by Django 5.1.6 on 2025-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospital_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
