# Generated by Django 5.1.6 on 2025-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='In-Person', max_length=10),
        ),
    ]
