# Generated by Django 5.1.6 on 2025-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
