# Generated by Django 5.1.6 on 2025-03-03 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ambulance_ambulancebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancebooking',
            name='pickup_location',
            field=models.CharField(db_default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ambulancebooking',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance'),
        ),
        migrations.AlterField(
            model_name='ambulancebooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulancebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
