# Generated by Django 5.1.6 on 2025-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ambulancebooking_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='affiliated_hospitals',
            field=models.ManyToManyField(blank=True, to='core.hospital'),
        ),
    ]
