# Generated by Django 5.1.6 on 2025-03-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hospital_affiliated_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='current_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_doctors', to='core.hospital'),
        ),
    ]
