# Generated by Django 5.1.6 on 2025-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_affiliationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='affiliated_hospitals',
            field=models.ManyToManyField(related_name='doctors', to='core.hospital'),
        ),
    ]
