# Generated by Django 5.1.6 on 2025-03-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_doctor_hospital_alter_doctor_affiliated_hospitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='affiliated_hospitals',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='current_hospital',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='affiliated_hospitals',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.DeleteModel(
            name='AffiliationRequest',
        ),
    ]
