# Generated by Django 5.1.6 on 2025-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_doctor_affiliated_hospitals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='affiliated_hospitals',
            field=models.ManyToManyField(blank=True, to='core.hospital'),
        ),
    ]
