# Generated by Django 5.1.6 on 2025-03-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_doctorhospitalchatroom_doctorhospitalchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorhospitalchatmessage',
            old_name='room',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='doctorhospitalchatroom',
            name='created_at',
        ),
    ]
