# Generated by Django 5.1.6 on 2025-03-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_doctorhospitalchatroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
