# Generated by Django 5.1.6 on 2025-03-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_appointment_appointment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
