# Generated by Django 5.1.6 on 2025-03-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_doctor_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
