# Generated by Django 5.1.6 on 2025-03-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_doctor_appointment_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Prescription Sent', 'Prescription Sent'), ('Pending Payment', 'Pending Payment'), ('Payment Completed', 'Payment Completed'), ('Medicine Given', 'Medicine Given')], default='Prescription Sent', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.prescription')),
            ],
        ),
    ]
