# Generated by Django 5.1.6 on 2025-03-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_prescription_is_completed_prescription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
