# Generated by Django 5.1.6 on 2025-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_prescription_status_prescription_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpg', upload_to='doctor_profiles/'),
        ),
    ]
