# Generated by Django 5.1.6 on 2025-03-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_patientchatroom_patientmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmessage',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='patientmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='patientChatRoom',
        ),
        migrations.DeleteModel(
            name='patientMessage',
        ),
    ]
